# Generated by Django 4.2.3 on 2023-07-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(help_text='Текст, который будет отображен в верхней части блока преимуществ', max_length=32, verbose_name='Верхний текст')),
                ('middle', models.CharField(help_text='Текст, который будет отображен в середине блока преимуществ', max_length=32, verbose_name='Средний текст')),
                ('bottom', models.CharField(help_text='Текст, который будет отображен в нижней части блока преимуществ', max_length=32, verbose_name='Нижний текст')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
