# Generated by Django 4.2.3 on 2023-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='href',
            field=models.SlugField(blank=True, help_text='Путь ссылки в браузере. Старайтесь делать коротким!', null=True, unique=True, verbose_name='Путь ссылки'),
        ),
    ]
