# Generated by Django 4.2.3 on 2023-07-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_alter_navigationlink_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlink',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Позиция Ссылки В Навигационной Панели', verbose_name='Приоритет Ссылки'),
        ),
    ]
