# Generated by Django 4.2.3 on 2023-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_navigationlink_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Позиция Ссылки В Навигационной Панели', unique=True, verbose_name='Приоритет Ссылки'),
        ),
    ]
